# Generated by Django 3.1.6 on 2021-07-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dept', models.CharField(max_length=200)),
                ('mail_dept', models.EmailField(max_length=254)),
                ('numero_dept', models.CharField(max_length=13)),
                ('description_dept', models.TextField()),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=200)),
                ('code_matiere', models.CharField(max_length=100)),
                ('coef_matiere', models.FloatField()),
                ('credit_matiere', models.FloatField()),
                ('quota_horaire', models.IntegerField()),
                ('description_matiere', models.TextField()),
                ('prof', models.ManyToManyField(related_name='prof_matiere', to='users.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='UE_matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_UE', models.CharField(max_length=200)),
                ('code_UE', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.classe')),
                ('matieres', models.ManyToManyField(related_name='matiere_ue', to='departement.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='ProfDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isChefDept', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.department')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=200)),
                ('description_niveau', models.TextField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.department')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant_Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=200)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.niveau'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.department'),
        ),
    ]
