# Generated by Django 3.1.6 on 2021-07-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description_dept',
            field=models.TextField(null=True),
        ),
    ]
