# Generated by Django 3.1.6 on 2021-07-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_auto_20210730_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveau',
            name='dept',
        ),
    ]
