# Generated by Django 3.1.6 on 2021-07-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0003_remove_niveau_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.department'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.niveau'),
        ),
    ]
